#main program
import exceptions

def main():
    
    exceptions.open_a_file_error('myfile')

    

main()
